spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring?serverTimezone=UTC&useSSL=false
    username: spring
    password: spring
  
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true